name: hmlylab packages
run-name: ${{ github.event.head_commit.message }}
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pkg.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
  
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build logger package
        run: go build -v ./...
        
      - name: Test Package
        run: go test -v ./...

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          make_latest: true
          tag_name: ${{github.ref_name}}
          token: ${{github.token}}
          generate_release_notes: true
